name: Test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Lint, Format, Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: ./next
        run: bun install --frozen-lockfile

      - name: Run Checks
        working-directory: ./next
        run: bun run check